language: cpp
dist: xenial
notifications:
  email: false

# Define builds on mulitple OS/compiler combinations.
# Feel free to add/remove entries from this list.
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7"

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - lcov
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"


before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build

install:
  - cd $PARENTDIR/build
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - make

script:
  - make

after_success:
  - cd $PARENTDIR/build
